# Generated by https://quicktype.io

from enum import Enum
from datetime import datetime
from typing import List, Any


class Email(Enum):
    GALIB_GMAIL_COM = "galib@gmail.com"


class Username(Enum):
    GALIB = "galib"


class Owner:
    id: int
    last_login: datetime
    is_superuser: bool
    username: Username
    first_name: str
    last_name: str
    email: Email
    is_staff: bool
    is_active: bool
    date_joined: datetime
    groups: List[Any]
    user_permissions: List[Any]

    def __init__(self, id: int, last_login: datetime, is_superuser: bool, username: Username, first_name: str, last_name: str, email: Email, is_staff: bool, is_active: bool, date_joined: datetime, groups: List[Any], user_permissions: List[Any]) -> None:
        self.id = id
        self.last_login = last_login
        self.is_superuser = is_superuser
        self.username = username
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.is_staff = is_staff
        self.is_active = is_active
        self.date_joined = date_joined
        self.groups = groups
        self.user_permissions = user_permissions


class PostElement:
    title: str
    id: int
    description: str
    owner: Owner

    def __init__(self, title: str, id: int, description: str, owner: Owner) -> None:
        self.title = title
        self.id = id
        self.description = description
        self.owner = owner
